// This file is generated by Tools/cases_generator/abstract_interpreter_generator.py
// from:
//   Python/tier2_specializer.c
// Do not edit!

        case _NOP: {
            DEBUG_PRINTF();
            break;
        }

        case _RESUME_CHECK: {
            DEBUG_PRINTF();
            break;
        }

        /* _INSTRUMENTED_RESUME is not a viable micro-op for tier 2 */

        case _LOAD_FAST_CHECK: {
            SpecializerValue *value;
            DEBUG_PRINTF();
            value = UNKNOWN();
            stack_pointer[0] = value;
            stack_pointer += 1;
            break;
        }

        case _LOAD_FAST: {
            SpecializerValue *value;
            DEBUG_PRINTF();
            value = UNKNOWN();
            stack_pointer[0] = value;
            stack_pointer += 1;
            break;
        }

        case _LOAD_FAST_AND_CLEAR: {
            SpecializerValue *value;
            DEBUG_PRINTF();
            value = UNKNOWN();
            stack_pointer[0] = value;
            stack_pointer += 1;
            break;
        }

        case _LOAD_CONST: {
            SpecializerValue *value;
            DEBUG_PRINTF();
            PyObject *k = PyTuple_GET_ITEM(code->co_consts, oparg);
            value = new_constant(k, space);
            REPLACE_OPCODE(_Py_IsImmortal(k) ?
                       _LOAD_INLINE_IMMORTAL_CONST :
                _LOAD_INLINE_CONST);
            this_instr->operand = (uintptr_t)k;
            stack_pointer[0] = value;
            stack_pointer += 1;
            break;
        }

        case _STORE_FAST: {
            SpecializerValue *value;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            stack_pointer += -1;
            break;
        }

        case _POP_TOP: {
            SpecializerValue *value;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            stack_pointer += -1;
            break;
        }

        case _PUSH_NULL: {
            SpecializerValue *res;
            DEBUG_PRINTF();
            res = UNKNOWN();
            stack_pointer[0] = res;
            stack_pointer += 1;
            break;
        }

        case _END_SEND: {
            SpecializerValue *value;
            SpecializerValue *receiver;
            value = stack_pointer[-1];
            receiver = stack_pointer[-2];
            DEBUG_PRINTF(receiver, value);
            DECREF(receiver);
            DECREF(value);
            value = UNKNOWN();
            stack_pointer[-2] = value;
            stack_pointer += -1;
            break;
        }

        case _UNARY_NEGATIVE: {
            SpecializerValue *value;
            SpecializerValue *res;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            res = UNKNOWN();
            stack_pointer[-1] = res;
            break;
        }

        case _UNARY_NOT: {
            SpecializerValue *value;
            SpecializerValue *res;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            res = UNKNOWN();
            stack_pointer[-1] = res;
            break;
        }

        case _TO_BOOL: {
            SpecializerValue *value;
            SpecializerValue *res;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            res = UNKNOWN();
            stack_pointer[-1] = res;
            break;
        }

        case _TO_BOOL_BOOL: {
            SpecializerValue *value;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            if (is_bool(value)) {
                REPLACE_OPCODE(_NOP);
            }
            else {
                promote_to_type(value, &PyBool_Type);
            }
            break;
        }

        case _TO_BOOL_INT: {
            SpecializerValue *value;
            SpecializerValue *res;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            res = UNKNOWN();
            stack_pointer[-1] = res;
            break;
        }

        case _TO_BOOL_LIST: {
            SpecializerValue *value;
            SpecializerValue *res;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            res = UNKNOWN();
            stack_pointer[-1] = res;
            break;
        }

        case _TO_BOOL_NONE: {
            SpecializerValue *value;
            SpecializerValue *res;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            if (get_constant(value) == Py_None) {
                REPLACE_OPCODE(_POP_TOP);
            }
            res = new_constant(Py_False, space);
            stack_pointer[-1] = res;
            break;
        }

        case _TO_BOOL_STR: {
            SpecializerValue *value;
            SpecializerValue *res;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            res = UNKNOWN();
            stack_pointer[-1] = res;
            break;
        }

        case _TO_BOOL_ALWAYS_TRUE: {
            SpecializerValue *value;
            SpecializerValue *res;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            res = UNKNOWN();
            stack_pointer[-1] = res;
            break;
        }

        case _UNARY_INVERT: {
            SpecializerValue *value;
            SpecializerValue *res;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            res = UNKNOWN();
            stack_pointer[-1] = res;
            break;
        }

        case _GUARD_BOTH_INT: {
            SpecializerValue *right;
            SpecializerValue *left;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            if (is_int(left)) {
                REPLACE_OPCODE(is_int(right) ? _NOP : _GUARD_TOS_INT);
            }
            else if (is_int(right)) {
                REPLACE_OPCODE(_GUARD_NOS_INT);
            }
            promote_to_type(left, &PyLong_Type);
            promote_to_type(right, &PyLong_Type);
            break;
        }

        case _GUARD_TOS_INT: {
            DEBUG_PRINTF();
            break;
        }

        case _GUARD_NOS_INT: {
            DEBUG_PRINTF();
            break;
        }

        case _BINARY_OP_MULTIPLY_INT: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *res;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            res = new_from_type(&PyLong_Type, space);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _BINARY_OP_ADD_INT: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *res;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            res = new_from_type(&PyLong_Type, space);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _BINARY_OP_SUBTRACT_INT: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *res;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            res = new_from_type(&PyLong_Type, space);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _GUARD_BOTH_FLOAT: {
            SpecializerValue *right;
            SpecializerValue *left;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            if (is_float(left)) {
                REPLACE_OPCODE(is_float(right) ? _NOP : _GUARD_TOS_FLOAT);
            }
            else if (is_float(right)) {
                REPLACE_OPCODE(_GUARD_NOS_FLOAT);
            }
            promote_to_type(left, &PyFloat_Type);
            promote_to_type(right, &PyFloat_Type);
            break;
        }

        case _GUARD_TOS_FLOAT: {
            DEBUG_PRINTF();
            break;
        }

        case _GUARD_NOS_FLOAT: {
            DEBUG_PRINTF();
            break;
        }

        case _BINARY_OP_MULTIPLY_FLOAT: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *res;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            res = new_from_type(&PyFloat_Type, space);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _BINARY_OP_ADD_FLOAT: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *res;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            res = new_from_type(&PyFloat_Type, space);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _BINARY_OP_SUBTRACT_FLOAT: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *res;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            res = new_from_type(&PyFloat_Type, space);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _GUARD_BOTH_UNICODE: {
            DEBUG_PRINTF();
            break;
        }

        case _BINARY_OP_ADD_UNICODE: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *res;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            DECREF(left);
            DECREF(right);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _BINARY_SUBSCR: {
            SpecializerValue *sub;
            SpecializerValue *container;
            SpecializerValue *res;
            sub = stack_pointer[-1];
            container = stack_pointer[-2];
            DEBUG_PRINTF(container, sub);
            DECREF(container);
            DECREF(sub);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _BINARY_SLICE: {
            SpecializerValue *stop;
            SpecializerValue *start;
            SpecializerValue *container;
            SpecializerValue *res;
            stop = stack_pointer[-1];
            start = stack_pointer[-2];
            container = stack_pointer[-3];
            DEBUG_PRINTF(container, start, stop);
            DECREF(container);
            DECREF(start);
            DECREF(stop);
            res = UNKNOWN();
            stack_pointer[-3] = res;
            stack_pointer += -2;
            break;
        }

        case _STORE_SLICE: {
            SpecializerValue *stop;
            SpecializerValue *start;
            SpecializerValue *container;
            SpecializerValue *v;
            stop = stack_pointer[-1];
            start = stack_pointer[-2];
            container = stack_pointer[-3];
            v = stack_pointer[-4];
            DEBUG_PRINTF(v, container, start, stop);
            DECREF(v);
            DECREF(container);
            DECREF(start);
            DECREF(stop);
            stack_pointer += -4;
            break;
        }

        case _BINARY_SUBSCR_LIST_INT: {
            SpecializerValue *sub;
            SpecializerValue *list;
            SpecializerValue *res;
            sub = stack_pointer[-1];
            list = stack_pointer[-2];
            DEBUG_PRINTF(list, sub);
            DECREF(list);
            DECREF(sub);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _BINARY_SUBSCR_STR_INT: {
            SpecializerValue *sub;
            SpecializerValue *str;
            SpecializerValue *res;
            sub = stack_pointer[-1];
            str = stack_pointer[-2];
            DEBUG_PRINTF(str, sub);
            DECREF(str);
            DECREF(sub);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _BINARY_SUBSCR_TUPLE_INT: {
            SpecializerValue *sub;
            SpecializerValue *tuple;
            SpecializerValue *res;
            sub = stack_pointer[-1];
            tuple = stack_pointer[-2];
            DEBUG_PRINTF(tuple, sub);
            DECREF(tuple);
            DECREF(sub);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _BINARY_SUBSCR_DICT: {
            SpecializerValue *sub;
            SpecializerValue *dict;
            SpecializerValue *res;
            sub = stack_pointer[-1];
            dict = stack_pointer[-2];
            DEBUG_PRINTF(dict, sub);
            DECREF(dict);
            DECREF(sub);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        /* _BINARY_SUBSCR_GETITEM is not a viable micro-op for tier 2 */

        case _LIST_APPEND: {
            SpecializerValue *v;
            v = stack_pointer[-1];
            DEBUG_PRINTF(v);
            DECREF(v);
            stack_pointer += -1;
            break;
        }

        case _SET_ADD: {
            SpecializerValue *v;
            v = stack_pointer[-1];
            DEBUG_PRINTF(v);
            DECREF(v);
            stack_pointer += -1;
            break;
        }

        case _STORE_SUBSCR: {
            SpecializerValue *sub;
            SpecializerValue *container;
            SpecializerValue *v;
            sub = stack_pointer[-1];
            container = stack_pointer[-2];
            v = stack_pointer[-3];
            DEBUG_PRINTF(v, container, sub);
            DECREF(v);
            DECREF(container);
            DECREF(sub);
            stack_pointer += -3;
            break;
        }

        case _STORE_SUBSCR_LIST_INT: {
            SpecializerValue *sub;
            SpecializerValue *list;
            SpecializerValue *value;
            sub = stack_pointer[-1];
            list = stack_pointer[-2];
            value = stack_pointer[-3];
            DEBUG_PRINTF(value, list, sub);
            DECREF(value);
            DECREF(list);
            DECREF(sub);
            stack_pointer += -3;
            break;
        }

        case _STORE_SUBSCR_DICT: {
            SpecializerValue *sub;
            SpecializerValue *dict;
            SpecializerValue *value;
            sub = stack_pointer[-1];
            dict = stack_pointer[-2];
            value = stack_pointer[-3];
            DEBUG_PRINTF(value, dict, sub);
            DECREF(value);
            DECREF(dict);
            DECREF(sub);
            stack_pointer += -3;
            break;
        }

        case _DELETE_SUBSCR: {
            SpecializerValue *sub;
            SpecializerValue *container;
            sub = stack_pointer[-1];
            container = stack_pointer[-2];
            DEBUG_PRINTF(container, sub);
            DECREF(container);
            DECREF(sub);
            stack_pointer += -2;
            break;
        }

        case _CALL_INTRINSIC_1: {
            SpecializerValue *value;
            SpecializerValue *res;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            res = UNKNOWN();
            stack_pointer[-1] = res;
            break;
        }

        case _CALL_INTRINSIC_2: {
            SpecializerValue *value1;
            SpecializerValue *value2;
            SpecializerValue *res;
            value1 = stack_pointer[-1];
            value2 = stack_pointer[-2];
            DEBUG_PRINTF(value2, value1);
            DECREF(value2);
            DECREF(value1);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _POP_FRAME: {
            SpecializerValue *retval;
            retval = stack_pointer[-1];
            DEBUG_PRINTF(retval);
            (void)retval;
            return modified;
            stack_pointer += -1;
            break;
        }

        /* _INSTRUMENTED_RETURN_VALUE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_RETURN_CONST is not a viable micro-op for tier 2 */

        case _GET_AITER: {
            SpecializerValue *obj;
            SpecializerValue *iter;
            obj = stack_pointer[-1];
            DEBUG_PRINTF(obj);
            DECREF(obj);
            iter = UNKNOWN();
            stack_pointer[-1] = iter;
            break;
        }

        case _GET_ANEXT: {
            SpecializerValue *awaitable;
            DEBUG_PRINTF();
            awaitable = UNKNOWN();
            stack_pointer[0] = awaitable;
            stack_pointer += 1;
            break;
        }

        case _GET_AWAITABLE: {
            SpecializerValue *iterable;
            SpecializerValue *iter;
            iterable = stack_pointer[-1];
            DEBUG_PRINTF(iterable);
            DECREF(iterable);
            iter = UNKNOWN();
            stack_pointer[-1] = iter;
            break;
        }

        /* _SEND is not a viable micro-op for tier 2 */

        /* _SEND_GEN is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_YIELD_VALUE is not a viable micro-op for tier 2 */

        case _POP_EXCEPT: {
            SpecializerValue *exc_value;
            exc_value = stack_pointer[-1];
            DEBUG_PRINTF(exc_value);
            DECREF(exc_value);
            stack_pointer += -1;
            break;
        }

        case _LOAD_ASSERTION_ERROR: {
            SpecializerValue *value;
            DEBUG_PRINTF();
            value = UNKNOWN();
            stack_pointer[0] = value;
            stack_pointer += 1;
            break;
        }

        case _LOAD_BUILD_CLASS: {
            SpecializerValue *bc;
            DEBUG_PRINTF();
            bc = UNKNOWN();
            stack_pointer[0] = bc;
            stack_pointer += 1;
            break;
        }

        case _STORE_NAME: {
            SpecializerValue *v;
            v = stack_pointer[-1];
            DEBUG_PRINTF(v);
            DECREF(v);
            stack_pointer += -1;
            break;
        }

        case _DELETE_NAME: {
            DEBUG_PRINTF();
            break;
        }

        case _UNPACK_SEQUENCE: {
            SpecializerValue *seq;
            seq = stack_pointer[-1];
            DEBUG_PRINTF(seq);
            DECREF(seq);
            stack_pointer += -1 + oparg;
            break;
        }

        case _UNPACK_SEQUENCE_TWO_TUPLE: {
            SpecializerValue *seq;
            SpecializerValue **values;
            seq = stack_pointer[-1];
            values = &stack_pointer[-1];
            DEBUG_PRINTF(seq);
            DECREF(seq);
            for (int _i = oparg; --_i >= 0;) {
                values[_i]  = UNKNOWN();
            }
            stack_pointer += -1 + oparg;
            break;
        }

        case _UNPACK_SEQUENCE_TUPLE: {
            SpecializerValue *seq;
            SpecializerValue **values;
            seq = stack_pointer[-1];
            values = &stack_pointer[-1];
            DEBUG_PRINTF(seq);
            DECREF(seq);
            for (int _i = oparg; --_i >= 0;) {
                values[_i]  = UNKNOWN();
            }
            stack_pointer += -1 + oparg;
            break;
        }

        case _UNPACK_SEQUENCE_LIST: {
            SpecializerValue *seq;
            SpecializerValue **values;
            seq = stack_pointer[-1];
            values = &stack_pointer[-1];
            DEBUG_PRINTF(seq);
            DECREF(seq);
            for (int _i = oparg; --_i >= 0;) {
                values[_i]  = UNKNOWN();
            }
            stack_pointer += -1 + oparg;
            break;
        }

        case _UNPACK_EX: {
            SpecializerValue *seq;
            seq = stack_pointer[-1];
            DEBUG_PRINTF(seq);
            DECREF(seq);
            stack_pointer += (oparg >> 8) + (oparg & 0xFF);
            break;
        }

        case _STORE_ATTR: {
            SpecializerValue *owner;
            SpecializerValue *v;
            owner = stack_pointer[-1];
            v = stack_pointer[-2];
            DEBUG_PRINTF(v, owner);
            DECREF(v);
            DECREF(owner);
            stack_pointer += -2;
            break;
        }

        case _DELETE_ATTR: {
            SpecializerValue *owner;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            stack_pointer += -1;
            break;
        }

        case _STORE_GLOBAL: {
            SpecializerValue *v;
            v = stack_pointer[-1];
            DEBUG_PRINTF(v);
            DECREF(v);
            stack_pointer += -1;
            break;
        }

        case _DELETE_GLOBAL: {
            DEBUG_PRINTF();
            break;
        }

        case _LOAD_LOCALS: {
            SpecializerValue *locals;
            DEBUG_PRINTF();
            locals = UNKNOWN();
            stack_pointer[0] = locals;
            stack_pointer += 1;
            break;
        }

        case _LOAD_FROM_DICT_OR_GLOBALS: {
            SpecializerValue *mod_or_class_dict;
            SpecializerValue *v;
            mod_or_class_dict = stack_pointer[-1];
            DEBUG_PRINTF(mod_or_class_dict);
            DECREF(mod_or_class_dict);
            v = UNKNOWN();
            stack_pointer[-1] = v;
            break;
        }

        case _LOAD_NAME: {
            SpecializerValue *v;
            DEBUG_PRINTF();
            v = UNKNOWN();
            stack_pointer[0] = v;
            stack_pointer += 1;
            break;
        }

        case _LOAD_GLOBAL: {
            SpecializerValue *res;
            SpecializerValue *null = NULL;
            DEBUG_PRINTF();
            res = UNKNOWN();
            null = NULL_VALUE();
            stack_pointer[0] = res;
            if (oparg & 1) stack_pointer[1] = null;
            stack_pointer += 1 + (oparg & 1);
            break;
        }

        case _GUARD_GLOBALS_VERSION: {
            DEBUG_PRINTF();
            break;
        }

        case _GUARD_BUILTINS_VERSION: {
            DEBUG_PRINTF();
            break;
        }

        case _LOAD_GLOBAL_MODULE: {
            SpecializerValue *res;
            SpecializerValue *null = NULL;
            DEBUG_PRINTF();
            res = UNKNOWN();
            null = NULL_VALUE();
            stack_pointer[0] = res;
            if (oparg & 1) stack_pointer[1] = null;
            stack_pointer += 1 + (oparg & 1);
            break;
        }

        case _LOAD_GLOBAL_BUILTINS: {
            SpecializerValue *res;
            SpecializerValue *null = NULL;
            DEBUG_PRINTF();
            res = UNKNOWN();
            null = NULL_VALUE();
            stack_pointer[0] = res;
            if (oparg & 1) stack_pointer[1] = null;
            stack_pointer += 1 + (oparg & 1);
            break;
        }

        case _DELETE_FAST: {
            DEBUG_PRINTF();
            break;
        }

        case _MAKE_CELL: {
            DEBUG_PRINTF();
            break;
        }

        case _DELETE_DEREF: {
            DEBUG_PRINTF();
            break;
        }

        case _LOAD_FROM_DICT_OR_DEREF: {
            SpecializerValue *class_dict;
            SpecializerValue *value;
            class_dict = stack_pointer[-1];
            DEBUG_PRINTF(class_dict);
            DECREF(class_dict);
            value = UNKNOWN();
            stack_pointer[-1] = value;
            break;
        }

        case _LOAD_DEREF: {
            SpecializerValue *value;
            DEBUG_PRINTF();
            value = UNKNOWN();
            stack_pointer[0] = value;
            stack_pointer += 1;
            break;
        }

        case _STORE_DEREF: {
            SpecializerValue *v;
            v = stack_pointer[-1];
            DEBUG_PRINTF(v);
            DECREF(v);
            stack_pointer += -1;
            break;
        }

        case _COPY_FREE_VARS: {
            DEBUG_PRINTF();
            break;
        }

        case _BUILD_STRING: {
            SpecializerValue **pieces;
            SpecializerValue *str;
            pieces = &stack_pointer[-oparg];
            DEBUG_PRINTF(pieces);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(pieces[_i]);
            }
            str = UNKNOWN();
            stack_pointer[-oparg] = str;
            stack_pointer += 1 - oparg;
            break;
        }

        case _BUILD_TUPLE: {
            SpecializerValue **values;
            SpecializerValue *tup;
            values = &stack_pointer[-oparg];
            DEBUG_PRINTF(values);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(values[_i]);
            }
            tup = UNKNOWN();
            stack_pointer[-oparg] = tup;
            stack_pointer += 1 - oparg;
            break;
        }

        case _BUILD_LIST: {
            SpecializerValue **values;
            SpecializerValue *list;
            values = &stack_pointer[-oparg];
            DEBUG_PRINTF(values);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(values[_i]);
            }
            list = UNKNOWN();
            stack_pointer[-oparg] = list;
            stack_pointer += 1 - oparg;
            break;
        }

        case _LIST_EXTEND: {
            SpecializerValue *iterable;
            iterable = stack_pointer[-1];
            DEBUG_PRINTF(iterable);
            DECREF(iterable);
            stack_pointer += -1;
            break;
        }

        case _SET_UPDATE: {
            SpecializerValue *iterable;
            iterable = stack_pointer[-1];
            DEBUG_PRINTF(iterable);
            DECREF(iterable);
            stack_pointer += -1;
            break;
        }

        case _BUILD_SET: {
            SpecializerValue **values;
            SpecializerValue *set;
            values = &stack_pointer[-oparg];
            DEBUG_PRINTF(values);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(values[_i]);
            }
            set = UNKNOWN();
            stack_pointer[-oparg] = set;
            stack_pointer += 1 - oparg;
            break;
        }

        case _BUILD_MAP: {
            SpecializerValue **values;
            SpecializerValue *map;
            values = &stack_pointer[-oparg*2];
            DEBUG_PRINTF(values);
            for (int _i = oparg*2; --_i >= 0;) {
                DECREF(values[_i]);
            }
            map = UNKNOWN();
            stack_pointer[-oparg*2] = map;
            stack_pointer += 1 - oparg*2;
            break;
        }

        case _SETUP_ANNOTATIONS: {
            DEBUG_PRINTF();
            break;
        }

        case _BUILD_CONST_KEY_MAP: {
            SpecializerValue *keys;
            SpecializerValue **values;
            SpecializerValue *map;
            keys = stack_pointer[-1];
            values = &stack_pointer[-1 - oparg];
            DEBUG_PRINTF(values, keys);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(values[_i]);
            }
            DECREF(keys);
            map = UNKNOWN();
            stack_pointer[-1 - oparg] = map;
            stack_pointer += -oparg;
            break;
        }

        case _DICT_UPDATE: {
            SpecializerValue *update;
            update = stack_pointer[-1];
            DEBUG_PRINTF(update);
            DECREF(update);
            stack_pointer += -1;
            break;
        }

        case _DICT_MERGE: {
            SpecializerValue *update;
            update = stack_pointer[-1];
            DEBUG_PRINTF(update);
            DECREF(update);
            stack_pointer += -1;
            break;
        }

        case _MAP_ADD: {
            SpecializerValue *value;
            SpecializerValue *key;
            value = stack_pointer[-1];
            key = stack_pointer[-2];
            DEBUG_PRINTF(key, value);
            DECREF(key);
            DECREF(value);
            stack_pointer += -2;
            break;
        }

        /* _INSTRUMENTED_LOAD_SUPER_ATTR is not a viable micro-op for tier 2 */

        case _LOAD_SUPER_ATTR_ATTR: {
            SpecializerValue *self;
            SpecializerValue *class;
            SpecializerValue *global_super;
            SpecializerValue *attr;
            self = stack_pointer[-1];
            class = stack_pointer[-2];
            global_super = stack_pointer[-3];
            DEBUG_PRINTF(global_super, class, self);
            DECREF(global_super);
            DECREF(class);
            DECREF(self);
            attr = UNKNOWN();
            stack_pointer[-3] = attr;
            stack_pointer += -2 + ((0) ? 1 : 0);
            break;
        }

        case _LOAD_SUPER_ATTR_METHOD: {
            SpecializerValue *self;
            SpecializerValue *class;
            SpecializerValue *global_super;
            SpecializerValue *attr;
            SpecializerValue *self_or_null;
            self = stack_pointer[-1];
            class = stack_pointer[-2];
            global_super = stack_pointer[-3];
            DEBUG_PRINTF(global_super, class, self);
            DECREF(global_super);
            DECREF(class);
            DECREF(self);
            attr = UNKNOWN();
            self_or_null = UNKNOWN();
            stack_pointer[-3] = attr;
            stack_pointer[-2] = self_or_null;
            stack_pointer += -1;
            break;
        }

        case _LOAD_ATTR: {
            SpecializerValue *owner;
            SpecializerValue *attr;
            SpecializerValue *self_or_null = NULL;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            attr = UNKNOWN();
            self_or_null = UNKNOWN();
            stack_pointer[-1] = attr;
            if (oparg & 1) stack_pointer[0] = self_or_null;
            stack_pointer += (oparg & 1);
            break;
        }

        case _GUARD_TYPE_VERSION: {
            DEBUG_PRINTF();
            break;
        }

        case _CHECK_MANAGED_OBJECT_HAS_VALUES: {
            DEBUG_PRINTF();
            break;
        }

        case _LOAD_ATTR_INSTANCE_VALUE: {
            SpecializerValue *owner;
            SpecializerValue *attr;
            SpecializerValue *null = NULL;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            attr = UNKNOWN();
            null = NULL_VALUE();
            stack_pointer[-1] = attr;
            if (oparg & 1) stack_pointer[0] = null;
            stack_pointer += (oparg & 1);
            break;
        }

        case _CHECK_ATTR_MODULE: {
            DEBUG_PRINTF();
            break;
        }

        case _LOAD_ATTR_MODULE: {
            SpecializerValue *owner;
            SpecializerValue *attr;
            SpecializerValue *null = NULL;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            attr = UNKNOWN();
            null = NULL_VALUE();
            stack_pointer[-1] = attr;
            if (oparg & 1) stack_pointer[0] = null;
            stack_pointer += (oparg & 1);
            break;
        }

        case _CHECK_ATTR_WITH_HINT: {
            DEBUG_PRINTF();
            break;
        }

        case _LOAD_ATTR_WITH_HINT: {
            SpecializerValue *owner;
            SpecializerValue *attr;
            SpecializerValue *null = NULL;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            attr = UNKNOWN();
            null = NULL_VALUE();
            stack_pointer[-1] = attr;
            if (oparg & 1) stack_pointer[0] = null;
            stack_pointer += (oparg & 1);
            break;
        }

        case _LOAD_ATTR_SLOT: {
            SpecializerValue *owner;
            SpecializerValue *attr;
            SpecializerValue *null = NULL;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            attr = UNKNOWN();
            null = NULL_VALUE();
            stack_pointer[-1] = attr;
            if (oparg & 1) stack_pointer[0] = null;
            stack_pointer += (oparg & 1);
            break;
        }

        case _CHECK_ATTR_CLASS: {
            DEBUG_PRINTF();
            break;
        }

        case _LOAD_ATTR_CLASS: {
            SpecializerValue *owner;
            SpecializerValue *attr;
            SpecializerValue *null = NULL;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            attr = UNKNOWN();
            null = NULL_VALUE();
            stack_pointer[-1] = attr;
            if (oparg & 1) stack_pointer[0] = null;
            stack_pointer += (oparg & 1);
            break;
        }

        /* _LOAD_ATTR_PROPERTY is not a viable micro-op for tier 2 */

        /* _LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN is not a viable micro-op for tier 2 */

        case _GUARD_DORV_VALUES: {
            DEBUG_PRINTF();
            break;
        }

        case _STORE_ATTR_INSTANCE_VALUE: {
            SpecializerValue *owner;
            SpecializerValue *value;
            owner = stack_pointer[-1];
            value = stack_pointer[-2];
            DEBUG_PRINTF(value, owner);
            DECREF(value);
            DECREF(owner);
            stack_pointer += -2;
            break;
        }

        /* _STORE_ATTR_WITH_HINT is not a viable micro-op for tier 2 */

        case _STORE_ATTR_SLOT: {
            SpecializerValue *owner;
            SpecializerValue *value;
            owner = stack_pointer[-1];
            value = stack_pointer[-2];
            DEBUG_PRINTF(value, owner);
            DECREF(value);
            DECREF(owner);
            stack_pointer += -2;
            break;
        }

        case _COMPARE_OP: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *res;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            DECREF(left);
            DECREF(right);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _COMPARE_OP_FLOAT: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *res;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            DECREF(left);
            DECREF(right);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _COMPARE_OP_INT: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *res;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            DECREF(left);
            DECREF(right);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _COMPARE_OP_STR: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *res;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            DECREF(left);
            DECREF(right);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _IS_OP: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *b;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            DECREF(left);
            DECREF(right);
            b = UNKNOWN();
            stack_pointer[-2] = b;
            stack_pointer += -1;
            break;
        }

        case _CONTAINS_OP: {
            SpecializerValue *right;
            SpecializerValue *left;
            SpecializerValue *b;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            DEBUG_PRINTF(left, right);
            DECREF(left);
            DECREF(right);
            b = UNKNOWN();
            stack_pointer[-2] = b;
            stack_pointer += -1;
            break;
        }

        case _CHECK_EG_MATCH: {
            SpecializerValue *match_type;
            SpecializerValue *exc_value;
            SpecializerValue *rest;
            SpecializerValue *match;
            match_type = stack_pointer[-1];
            exc_value = stack_pointer[-2];
            DEBUG_PRINTF(exc_value, match_type);
            DECREF(exc_value);
            DECREF(match_type);
            rest = UNKNOWN();
            match = UNKNOWN();
            stack_pointer[-2] = rest;
            stack_pointer[-1] = match;
            break;
        }

        case _CHECK_EXC_MATCH: {
            SpecializerValue *right;
            SpecializerValue *b;
            right = stack_pointer[-1];
            DEBUG_PRINTF(right);
            DECREF(right);
            b = UNKNOWN();
            stack_pointer[-1] = b;
            break;
        }

        /* _JUMP_BACKWARD is not a viable micro-op for tier 2 */

        /* _POP_JUMP_IF_FALSE is not a viable micro-op for tier 2 */

        /* _POP_JUMP_IF_TRUE is not a viable micro-op for tier 2 */

        case _IS_NONE: {
            SpecializerValue *value;
            SpecializerValue *b;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            b = UNKNOWN();
            stack_pointer[-1] = b;
            break;
        }

        case _GET_LEN: {
            SpecializerValue *len_o;
            DEBUG_PRINTF();
            len_o = UNKNOWN();
            stack_pointer[0] = len_o;
            stack_pointer += 1;
            break;
        }

        case _MATCH_CLASS: {
            SpecializerValue *names;
            SpecializerValue *type;
            SpecializerValue *subject;
            SpecializerValue *attrs;
            names = stack_pointer[-1];
            type = stack_pointer[-2];
            subject = stack_pointer[-3];
            DEBUG_PRINTF(subject, type, names);
            DECREF(subject);
            DECREF(type);
            DECREF(names);
            attrs = UNKNOWN();
            stack_pointer[-3] = attrs;
            stack_pointer += -2;
            break;
        }

        case _MATCH_MAPPING: {
            SpecializerValue *res;
            DEBUG_PRINTF();
            res = UNKNOWN();
            stack_pointer[0] = res;
            stack_pointer += 1;
            break;
        }

        case _MATCH_SEQUENCE: {
            SpecializerValue *res;
            DEBUG_PRINTF();
            res = UNKNOWN();
            stack_pointer[0] = res;
            stack_pointer += 1;
            break;
        }

        case _MATCH_KEYS: {
            SpecializerValue *values_or_none;
            DEBUG_PRINTF();
            values_or_none = UNKNOWN();
            stack_pointer[0] = values_or_none;
            stack_pointer += 1;
            break;
        }

        case _GET_ITER: {
            SpecializerValue *iterable;
            SpecializerValue *iter;
            iterable = stack_pointer[-1];
            DEBUG_PRINTF(iterable);
            DECREF(iterable);
            iter = UNKNOWN();
            stack_pointer[-1] = iter;
            break;
        }

        case _GET_YIELD_FROM_ITER: {
            SpecializerValue *iterable;
            SpecializerValue *iter;
            iterable = stack_pointer[-1];
            DEBUG_PRINTF(iterable);
            DECREF(iterable);
            iter = UNKNOWN();
            stack_pointer[-1] = iter;
            break;
        }

        /* _FOR_ITER is not a viable micro-op for tier 2 */

        case _FOR_ITER_TIER_TWO: {
            SpecializerValue *next;
            DEBUG_PRINTF();
            next = UNKNOWN();
            stack_pointer[0] = next;
            stack_pointer += 1;
            break;
        }

        /* _INSTRUMENTED_FOR_ITER is not a viable micro-op for tier 2 */

        case _ITER_CHECK_LIST: {
            DEBUG_PRINTF();
            break;
        }

        /* _ITER_JUMP_LIST is not a viable micro-op for tier 2 */

        case _GUARD_NOT_EXHAUSTED_LIST: {
            DEBUG_PRINTF();
            break;
        }

        case _ITER_NEXT_LIST: {
            SpecializerValue *next;
            DEBUG_PRINTF();
            next = UNKNOWN();
            stack_pointer[0] = next;
            stack_pointer += 1;
            break;
        }

        case _ITER_CHECK_TUPLE: {
            DEBUG_PRINTF();
            break;
        }

        /* _ITER_JUMP_TUPLE is not a viable micro-op for tier 2 */

        case _GUARD_NOT_EXHAUSTED_TUPLE: {
            DEBUG_PRINTF();
            break;
        }

        case _ITER_NEXT_TUPLE: {
            SpecializerValue *next;
            DEBUG_PRINTF();
            next = UNKNOWN();
            stack_pointer[0] = next;
            stack_pointer += 1;
            break;
        }

        case _ITER_CHECK_RANGE: {
            DEBUG_PRINTF();
            break;
        }

        /* _ITER_JUMP_RANGE is not a viable micro-op for tier 2 */

        case _GUARD_NOT_EXHAUSTED_RANGE: {
            DEBUG_PRINTF();
            break;
        }

        case _ITER_NEXT_RANGE: {
            SpecializerValue *next;
            DEBUG_PRINTF();
            next = UNKNOWN();
            stack_pointer[0] = next;
            stack_pointer += 1;
            break;
        }

        /* _FOR_ITER_GEN is not a viable micro-op for tier 2 */

        case _BEFORE_ASYNC_WITH: {
            SpecializerValue *mgr;
            SpecializerValue *exit;
            SpecializerValue *res;
            mgr = stack_pointer[-1];
            DEBUG_PRINTF(mgr);
            DECREF(mgr);
            exit = UNKNOWN();
            res = UNKNOWN();
            stack_pointer[-1] = exit;
            stack_pointer[0] = res;
            stack_pointer += 1;
            break;
        }

        case _BEFORE_WITH: {
            SpecializerValue *mgr;
            SpecializerValue *exit;
            SpecializerValue *res;
            mgr = stack_pointer[-1];
            DEBUG_PRINTF(mgr);
            DECREF(mgr);
            exit = UNKNOWN();
            res = UNKNOWN();
            stack_pointer[-1] = exit;
            stack_pointer[0] = res;
            stack_pointer += 1;
            break;
        }

        case _WITH_EXCEPT_START: {
            SpecializerValue *res;
            DEBUG_PRINTF();
            res = UNKNOWN();
            stack_pointer[0] = res;
            stack_pointer += 1;
            break;
        }

        case _PUSH_EXC_INFO: {
            SpecializerValue *new_exc;
            SpecializerValue *prev_exc;
            new_exc = stack_pointer[-1];
            DEBUG_PRINTF(new_exc);
            DECREF(new_exc);
            prev_exc = UNKNOWN();
            new_exc = UNKNOWN();
            stack_pointer[-1] = prev_exc;
            stack_pointer[0] = new_exc;
            stack_pointer += 1;
            break;
        }

        case _GUARD_DORV_VALUES_INST_ATTR_FROM_DICT: {
            DEBUG_PRINTF();
            break;
        }

        case _GUARD_KEYS_VERSION: {
            DEBUG_PRINTF();
            break;
        }

        case _LOAD_ATTR_METHOD_WITH_VALUES: {
            SpecializerValue *owner;
            SpecializerValue *attr;
            SpecializerValue *self = NULL;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            attr = UNKNOWN();
            self = UNKNOWN();
            stack_pointer[-1] = attr;
            if (1) stack_pointer[0] = self;
            stack_pointer += ((1) ? 1 : 0);
            break;
        }

        case _LOAD_ATTR_METHOD_NO_DICT: {
            SpecializerValue *owner;
            SpecializerValue *attr;
            SpecializerValue *self = NULL;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            attr = UNKNOWN();
            self = UNKNOWN();
            stack_pointer[-1] = attr;
            if (1) stack_pointer[0] = self;
            stack_pointer += ((1) ? 1 : 0);
            break;
        }

        case _LOAD_ATTR_NONDESCRIPTOR_WITH_VALUES: {
            SpecializerValue *owner;
            SpecializerValue *attr;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            attr = UNKNOWN();
            stack_pointer[-1] = attr;
            stack_pointer += ((0) ? 1 : 0);
            break;
        }

        case _LOAD_ATTR_NONDESCRIPTOR_NO_DICT: {
            SpecializerValue *owner;
            SpecializerValue *attr;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            attr = UNKNOWN();
            stack_pointer[-1] = attr;
            stack_pointer += ((0) ? 1 : 0);
            break;
        }

        case _CHECK_ATTR_METHOD_LAZY_DICT: {
            DEBUG_PRINTF();
            break;
        }

        case _LOAD_ATTR_METHOD_LAZY_DICT: {
            SpecializerValue *owner;
            SpecializerValue *attr;
            SpecializerValue *self = NULL;
            owner = stack_pointer[-1];
            DEBUG_PRINTF(owner);
            DECREF(owner);
            attr = UNKNOWN();
            self = UNKNOWN();
            stack_pointer[-1] = attr;
            if (1) stack_pointer[0] = self;
            stack_pointer += ((1) ? 1 : 0);
            break;
        }

        /* _INSTRUMENTED_CALL is not a viable micro-op for tier 2 */

        /* _CALL is not a viable micro-op for tier 2 */

        case _CHECK_CALL_BOUND_METHOD_EXACT_ARGS: {
            DEBUG_PRINTF();
            break;
        }

        case _INIT_CALL_BOUND_METHOD_EXACT_ARGS: {
            SpecializerValue *callable;
            SpecializerValue *func;
            SpecializerValue *self;
            callable = stack_pointer[-2];
            DEBUG_PRINTF(callable, unused);
            DECREF(callable);
            func = UNKNOWN();
            self = UNKNOWN();
            stack_pointer[-2] = func;
            stack_pointer[-1] = self;
            break;
        }

        case _CHECK_PEP_523: {
            DEBUG_PRINTF();
            break;
        }

        case _CHECK_FUNCTION_EXACT_ARGS: {
            DEBUG_PRINTF();
            break;
        }

        case _CHECK_STACK_SPACE: {
            DEBUG_PRINTF();
            break;
        }

        case _INIT_CALL_PY_EXACT_ARGS: {
            SpecializerValue **args;
            SpecializerValue *self_or_null;
            SpecializerValue *callable;
            SpecializerValue *new_frame;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, self_or_null, args);
            (void)callable;
            (void)self_or_null;
            (void)args;
            return modified;
            stack_pointer[-2 - oparg] = new_frame;
            stack_pointer += -1 - oparg;
            break;
        }

        case _PUSH_FRAME: {
            SpecializerValue *new_frame;
            new_frame = stack_pointer[-1];
            DEBUG_PRINTF(new_frame);
            (void)new_frame;
            return modified;
            stack_pointer += -1 + ((0) ? 1 : 0);
            break;
        }

        /* _CALL_PY_WITH_DEFAULTS is not a viable micro-op for tier 2 */

        case _CALL_TYPE_1: {
            SpecializerValue **args;
            SpecializerValue *null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, null, args);
            DECREF(callable);
            DECREF(null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        case _CALL_STR_1: {
            SpecializerValue **args;
            SpecializerValue *null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, null, args);
            DECREF(callable);
            DECREF(null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        case _CALL_TUPLE_1: {
            SpecializerValue **args;
            SpecializerValue *null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, null, args);
            DECREF(callable);
            DECREF(null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        /* _CALL_ALLOC_AND_ENTER_INIT is not a viable micro-op for tier 2 */

        case _EXIT_INIT_CHECK: {
            SpecializerValue *should_be_none;
            should_be_none = stack_pointer[-1];
            DEBUG_PRINTF(should_be_none);
            DECREF(should_be_none);
            stack_pointer += -1;
            break;
        }

        case _CALL_BUILTIN_CLASS: {
            SpecializerValue **args;
            SpecializerValue *self_or_null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, self_or_null, args);
            DECREF(callable);
            DECREF(self_or_null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        case _CALL_BUILTIN_O: {
            SpecializerValue **args;
            SpecializerValue *self_or_null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, self_or_null, args);
            DECREF(callable);
            DECREF(self_or_null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        case _CALL_BUILTIN_FAST: {
            SpecializerValue **args;
            SpecializerValue *self_or_null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, self_or_null, args);
            DECREF(callable);
            DECREF(self_or_null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        case _CALL_BUILTIN_FAST_WITH_KEYWORDS: {
            SpecializerValue **args;
            SpecializerValue *self_or_null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, self_or_null, args);
            DECREF(callable);
            DECREF(self_or_null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        case _CALL_LEN: {
            SpecializerValue **args;
            SpecializerValue *self_or_null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, self_or_null, args);
            DECREF(callable);
            DECREF(self_or_null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        case _CALL_ISINSTANCE: {
            SpecializerValue **args;
            SpecializerValue *self_or_null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, self_or_null, args);
            DECREF(callable);
            DECREF(self_or_null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_O: {
            SpecializerValue **args;
            SpecializerValue *self_or_null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, self_or_null, args);
            DECREF(callable);
            DECREF(self_or_null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS: {
            SpecializerValue **args;
            SpecializerValue *self_or_null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, self_or_null, args);
            DECREF(callable);
            DECREF(self_or_null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_NOARGS: {
            SpecializerValue **args;
            SpecializerValue *self_or_null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, self_or_null, args);
            DECREF(callable);
            DECREF(self_or_null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_FAST: {
            SpecializerValue **args;
            SpecializerValue *self_or_null;
            SpecializerValue *callable;
            SpecializerValue *res;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            callable = stack_pointer[-2 - oparg];
            DEBUG_PRINTF(callable, self_or_null, args);
            DECREF(callable);
            DECREF(self_or_null);
            for (int _i = oparg; --_i >= 0;) {
                DECREF(args[_i]);
            }
            res = UNKNOWN();
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            break;
        }

        /* _INSTRUMENTED_CALL_KW is not a viable micro-op for tier 2 */

        /* _CALL_KW is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_CALL_FUNCTION_EX is not a viable micro-op for tier 2 */

        /* _CALL_FUNCTION_EX is not a viable micro-op for tier 2 */

        case _MAKE_FUNCTION: {
            SpecializerValue *codeobj;
            SpecializerValue *func;
            codeobj = stack_pointer[-1];
            DEBUG_PRINTF(codeobj);
            DECREF(codeobj);
            func = UNKNOWN();
            stack_pointer[-1] = func;
            break;
        }

        case _SET_FUNCTION_ATTRIBUTE: {
            SpecializerValue *func;
            SpecializerValue *attr;
            func = stack_pointer[-1];
            attr = stack_pointer[-2];
            DEBUG_PRINTF(attr, func);
            DECREF(attr);
            DECREF(func);
            func = UNKNOWN();
            stack_pointer[-2] = func;
            stack_pointer += -1;
            break;
        }

        case _BUILD_SLICE: {
            SpecializerValue *step = NULL;
            SpecializerValue *stop;
            SpecializerValue *start;
            SpecializerValue *slice;
            if (oparg == 3) { step = stack_pointer[-((oparg == 3) ? 1 : 0)]; }
            stop = stack_pointer[-1 - ((oparg == 3) ? 1 : 0)];
            start = stack_pointer[-2 - ((oparg == 3) ? 1 : 0)];
            DEBUG_PRINTF(start, stop, step);
            DECREF(start);
            DECREF(stop);
            if (step != NULL) DECREF(step);
            slice = UNKNOWN();
            stack_pointer[-2 - ((oparg == 3) ? 1 : 0)] = slice;
            stack_pointer += -1 - ((oparg == 3) ? 1 : 0);
            break;
        }

        case _CONVERT_VALUE: {
            SpecializerValue *value;
            SpecializerValue *result;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            result = UNKNOWN();
            stack_pointer[-1] = result;
            break;
        }

        case _FORMAT_SIMPLE: {
            SpecializerValue *value;
            SpecializerValue *res;
            value = stack_pointer[-1];
            DEBUG_PRINTF(value);
            DECREF(value);
            res = UNKNOWN();
            stack_pointer[-1] = res;
            break;
        }

        case _FORMAT_WITH_SPEC: {
            SpecializerValue *fmt_spec;
            SpecializerValue *value;
            SpecializerValue *res;
            fmt_spec = stack_pointer[-1];
            value = stack_pointer[-2];
            DEBUG_PRINTF(value, fmt_spec);
            DECREF(value);
            DECREF(fmt_spec);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _COPY: {
            SpecializerValue *bottom;
            SpecializerValue *top;
            bottom = stack_pointer[-1 - (oparg-1)];
            DEBUG_PRINTF(bottom, unused);
            assert(oparg > 0);
            top = bottom;
            stack_pointer[0] = top;
            stack_pointer += 1;
            break;
        }

        case _BINARY_OP: {
            SpecializerValue *rhs;
            SpecializerValue *lhs;
            SpecializerValue *res;
            rhs = stack_pointer[-1];
            lhs = stack_pointer[-2];
            DEBUG_PRINTF(lhs, rhs);
            DECREF(lhs);
            DECREF(rhs);
            res = UNKNOWN();
            stack_pointer[-2] = res;
            stack_pointer += -1;
            break;
        }

        case _SWAP: {
            SpecializerValue *top;
            SpecializerValue *bottom;
            top = stack_pointer[-1];
            bottom = stack_pointer[-2 - (oparg-2)];
            DEBUG_PRINTF(bottom, unused, top);
            stack_pointer[-2 - (oparg-2)] = top;
            stack_pointer[-1] = bottom;
            break;
        }

        /* _INSTRUMENTED_INSTRUCTION is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_JUMP_FORWARD is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_JUMP_BACKWARD is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_TRUE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_FALSE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_NONE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_NOT_NONE is not a viable micro-op for tier 2 */

        case _GUARD_IS_TRUE_POP: {
            SpecializerValue *flag;
            flag = stack_pointer[-1];
            DEBUG_PRINTF(flag);
            modified |= guard_bool(this_instr, flag, Py_True);
            stack_pointer += -1;
            break;
        }

        case _GUARD_IS_FALSE_POP: {
            SpecializerValue *flag;
            flag = stack_pointer[-1];
            DEBUG_PRINTF(flag);
            modified |= guard_bool(this_instr, flag, Py_False);
            stack_pointer += -1;
            break;
        }

        case _GUARD_IS_NONE_POP: {
            SpecializerValue *flag;
            flag = stack_pointer[-1];
            DEBUG_PRINTF(flag);
            modified |= guard_none(this_instr, flag, 1);
            stack_pointer += -1;
            break;
        }

        case _GUARD_IS_NOT_NONE_POP: {
            SpecializerValue *flag;
            flag = stack_pointer[-1];
            DEBUG_PRINTF(flag);
            modified |= guard_none(this_instr, flag, 0);
            stack_pointer += -1;
            break;
        }

        case _JUMP_TO_TOP: {
            DEBUG_PRINTF();
            return modified;
            break;
        }

        case _SET_IP: {
            DEBUG_PRINTF();
            break;
        }

        case _SAVE_RETURN_OFFSET: {
            DEBUG_PRINTF();
            break;
        }

        case _EXIT_TRACE: {
            DEBUG_PRINTF();
            return modified;
            break;
        }

        case _INSERT: {
            SpecializerValue *top;
            top = stack_pointer[-1];
            DEBUG_PRINTF(unused, top);
            DECREF(top);
            top = UNKNOWN();
            stack_pointer[-1 - oparg] = top;
            break;
        }

        case _CHECK_VALIDITY: {
            DEBUG_PRINTF();
            break;
        }

        case _LOAD_INLINE_CONST: {
            SpecializerValue *res;
            DEBUG_PRINTF();
            res = UNKNOWN();
            stack_pointer[0] = res;
            stack_pointer += 1;
            break;
        }

        case _LOAD_INLINE_IMMORTAL_CONST: {
            SpecializerValue *res;
            DEBUG_PRINTF();
            res = UNKNOWN();
            stack_pointer[0] = res;
            stack_pointer += 1;
            break;
        }

